services:
    nginx:
        container_name: nginx
        build: requirements/nginx/
        depends_on:
            - wordpress
        networks: 
            - inception
        env_file: .env
        ports:
            - "443:443"
        volumes:
            - wordpress:/var/www/html
        restart: always

    mariadb:
        container_name: mariadb
        build: requirements/mariadb/
        networks:
            - inception
        env_file: .env
        volumes:
            - mariadb:${MARIADB_DATADIR}
        restart: always
        healthcheck:
            test: "mariadb-admin ping"
            interval: 2s
            timeout: 30s
            retries: 5

    wordpress:
        container_name: wordpress
        build: requirements/wordpress/
        depends_on:
            mariadb:
                condition: service_healthy
        networks: 
            - inception
        expose:
            - "9000"
        env_file: .env
        volumes:
            - wordpress:/var/www/html
        restart: always

volumes:
    mariadb:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tde-la-r/data/mariadb
    wordpress:
        driver: local
        driver_opts:
            type: none
            o: bind
            device: /home/tde-la-r/data/wordpress

networks:
    inception:
        driver: bridge
